# Generated by Django 5.1.7 on 2025-04-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='שם האוכל')),
                ('recepie', models.TextField(max_length=500, null=True, verbose_name='מתכון')),
            ],
        ),
    ]
