# Generated by Django 5.1.7 on 2025-04-02 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='rating',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='דירוג'),
        ),
    ]
