# Generated by Django 5.1.7 on 2025-04-02 09:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_foods', '0002_food_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='דירוג'),
        ),
        migrations.AlterField(
            model_name='food',
            name='recepie',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='מתכון'),
        ),
    ]
