# Generated by Django 5.1.7 on 2025-04-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_foods', '0003_alter_food_rating_alter_food_recepie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='name',
            new_name='food_name',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.CharField(default=1, max_length=30, verbose_name='מצרכים'),
            preserve_default=False,
        ),
    ]
