# Generated by Django 5.1.7 on 2025-05-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_foods', '0004_rename_name_food_food_name_food_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.TextField(max_length=300, verbose_name='מצרכים'),
        ),
    ]
