# Generated by Django 5.1.7 on 2025-05-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_foods', '0005_alter_food_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.TextField(max_length=1000, verbose_name='מצרכים'),
        ),
        migrations.AlterField(
            model_name='food',
            name='recepie',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='מתכון'),
        ),
    ]
