# Generated by Django 5.1.7 on 2025-05-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_foods', '0012_alter_author_author_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='שם האוכל')),
                ('writer', models.CharField(max_length=500, verbose_name='שם האוכל')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
