# Generated by Django 5.1.7 on 2025-05-24 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('japan_foods', '0013_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='japan_foods.food'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='author_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=500, verbose_name='תגובה'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.CharField(max_length=100, verbose_name='שם כותב'),
        ),
    ]
