# Generated by Django 5.1.7 on 2025-04-08 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='שם')),
                ('surname', models.CharField(max_length=255, verbose_name='משפחה')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='דואר אלקטרוני')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='טלפון')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='כותרת')),
                ('content', models.TextField(verbose_name='תוכן')),
                ('updated_at', models.DateTimeField(verbose_name='עדכון אחרון')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
            ],
        ),
    ]
